import { StyleSheet } from "react-native";

export const profileScreenStyles = StyleSheet.create({
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  stepContainer: {
    gap: 8,
    marginBottom: 8,
  },
  idCardBox: {
    width: "80%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    margin: 30,
    gap: 12,
},
  idCardIconBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
},
  idCardImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    resizeMode: "cover",
},
  idCardQR: {
    width: 20,
    height: 20,
    backgroundColor: "#ffffff",
    borderRadius: 2,
    borderWidth: 1,
    borderColor: "#155d26",
    justifyContent: "center",
    alignItems: "center",
},
  idCardName: {
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
},
  idCardAddressBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    backgroundColor: "#f0f0f5",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
},
  idCardAddress: {
    flex: 1,
    fontSize: 12,
    color: "#0a0a1a",
},
 idCardAddressCopy: {
    width: 28,
    height: 28,
    justifyContent: "center",
    alignItems: "center",
},
  idCardVerified: {
    width: 18,
    height: 18,
},
  profileBackButton: {
    flexDirection: "row",
    alignItems: "center",
    margin: 12
  },
  profileBackText: {
    color: "#fff",
    fontSize: 16,
    marginLeft: 8,
  },
  profileSafe: {
    flex: 1,
    backgroundColor: "#65d497",
  },
  profileScroll: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  profileTitle: {
    color: "#FFFFFF",
    fontSize: 32,
    fontWeight: "700",
    marginBottom: 8,
  },
  profileSubtitle: {
    color: "#24794a",
    fontSize: 15,
    marginBottom: 12,
  },
  profileSectionTitle: {
    color: "#084624",
    fontSize: 13,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 12,
    marginTop: 8,
  },
  profileCard: {
    backgroundColor: "#4cac77",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#2A2A35",
    padding: 4,
    marginBottom: 24,
  },
  profileRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
  },
  profileRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profileIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#1E1E28",
    alignItems: "center",
    justifyContent: "center",
  },
  profileIconBoxDevnet: {
    backgroundColor: "#2D2310",
  },
  profileLabel: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  profileSublabel: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  profileBadge: {
    backgroundColor: "#1E1E28",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  profileBadgeText: {
    color: "#14F195",
    fontSize: 14,
    fontWeight: "600",
  },
  profileDivider: {
    height: 1,
    backgroundColor: "#2A2A35",
    marginHorizontal: 14,
  },
  profileDangerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#1A1215",
    borderWidth: 1,
    borderColor: "#3D2023",
    paddingVertical: 16,
    borderRadius: 14,
  },
  profileDangerText: {
    color: "#efbf44",
    fontSize: 16,
    fontWeight: "600",
  },
  profileRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
});
