import { Platform, StyleSheet } from "react-native";
import { palette, radius } from "@mpay/styles/theme";

const displayFont = Platform.select({
  ios: "Bricolage Grotesque",
  android: "sans-serif-light",
  default: "sans-serif"
});

const bodyFont = Platform.select({
  ios: "Inter",
  android: "sans-serif",
  default: "sans-serif"
});

export const sendScreen = StyleSheet.create({
  /* ═══════════════════════════════════════════
     AMOUNT SCREEN (dark full-screen)
     ═══════════════════════════════════════════ */
  amountPage: {
    flex: 1,
    backgroundColor: palette.panelDark,
  },
  amountHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  sendFromLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 16,
    fontWeight: "500",
    fontFamily: bodyFont,
  },
  userPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  userPillText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  amountDisplayArea: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  currencyTogglePill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 12,
  },
  currencyToggleSymbol: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: bodyFont,
  },
  currencyToggleLabel: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  amountText: {
    color: "#fff",
    fontSize: 64,
    fontWeight: "700",
    letterSpacing: -2,
    fontFamily: displayFont,
  },
  amountTextEmpty: {
    opacity: 0.3,
  },
  numpad: {
    paddingHorizontal: 32,
    gap: 8,
    marginBottom: 16,
  },
  numpadRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  numpadKey: {
    width: 80,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
  },
  numpadDigit: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  numpadDot: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 28,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  amountBottom: {
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  memoInput: {
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 20,
    color: "rgba(255,255,255,0.5)",
    fontSize: 15,
    fontFamily: bodyFont,
    textAlign: "center" as const,
    letterSpacing: 0,
  },
  amountFooter: {
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    backgroundColor: palette.panelDark,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 40,
  },
  amountFooterInner: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerLabel: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 10,
    letterSpacing: 2.3,
    textTransform: "uppercase" as const,
    marginBottom: 4,
    fontFamily: bodyFont,
  },
  footerTitle: {
    color: "#fff",
    fontSize: 32,
    letterSpacing: -1,
    fontWeight: "300" as const,
    fontFamily: displayFont,
  },
  ctaCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  ctaCircleDisabled: {
    opacity: 0.5,
  },
  availableRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  availableText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 12,
    fontFamily: bodyFont,
  },

  /* ═══════════════════════════════════════════
     RECIPIENT SCREEN (light background)
     ═══════════════════════════════════════════ */
  recipientPage: {
    flex: 1,
    backgroundColor: palette.backgroundLight,
  },
  recipientHeader: {
    backgroundColor: palette.panelDark,
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 20,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
  },
  recipientHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  amountSummaryPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  amountSummaryText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  amountSummaryCurrency: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 13,
    fontWeight: "500",
    fontFamily: bodyFont,
  },
  editAmountButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  recipientContent: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  filterScroll: {
    marginBottom: 20,
    flexGrow: 0,
  },
  filterRow: {
    flexDirection: "row",
    gap: 10,
  },
  filterPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.borderLight,
    backgroundColor: palette.surfaceLight,
  },
  filterPillActive: {
    borderColor: palette.textPrimary,
    backgroundColor: palette.textPrimary,
  },
  filterPillText: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: "500",
    fontFamily: bodyFont,
  },
  filterPillTextActive: {
    color: "#fff",
  },
  searchInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: palette.surfaceSoft,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: palette.borderLight,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    color: palette.textPrimary,
    fontSize: 16,
    padding: 0,
    fontFamily: bodyFont,
    letterSpacing: 0,
  },
  sectionLabel: {
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: "600" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 1.2,
    marginBottom: 12,
    fontFamily: bodyFont,
  },
  recentRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 24,
  },
  recentItem: {
    alignItems: "center",
    gap: 6,
    width: 56,
  },
  recentAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.borderLight,
    alignItems: "center",
    justifyContent: "center",
  },
  recentAvatarText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  recentName: {
    color: palette.textMuted,
    fontSize: 11,
    fontFamily: bodyFont,
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f1f3",
  },
  contactAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.borderLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  contactAvatarText: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  contactMeta: {
    color: palette.textMuted,
    fontSize: 12,
    marginTop: 2,
    fontFamily: bodyFont,
  },
  contactChevron: {
    marginLeft: 8,
  },
  searchState: {
    color: palette.textMuted,
    fontSize: 11,
    marginBottom: 10,
    fontFamily: bodyFont,
  },
  searchError: {
    color: palette.danger,
    fontSize: 11,
    marginBottom: 10,
    fontFamily: bodyFont,
  },
  suggestionsCard: {
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: palette.borderLight,
    backgroundColor: palette.surfaceLight,
    marginBottom: 12,
    overflow: "hidden" as const,
  },
  suggestionRow: {
    minHeight: 52,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f1f3",
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  suggestionTag: {
    color: palette.textPrimary,
    fontSize: 13,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  suggestionMeta: {
    color: palette.textMuted,
    fontSize: 11,
    fontFamily: bodyFont,
  },

  /* ═══════════════════════════════════════════
     RECIPIENT PREVIEW CARD
     ═══════════════════════════════════════════ */
  previewCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.borderLight,
    backgroundColor: palette.surfaceLight,
    padding: 16,
    marginBottom: 20,
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  previewTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  previewAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: palette.panelDark,
    alignItems: "center",
    justifyContent: "center",
  },
  previewAvatarText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  previewName: {
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  previewTag: {
    color: palette.textSecondary,
    fontSize: 12,
    fontFamily: bodyFont,
    marginTop: 1,
  },
  previewWallet: {
    color: palette.textMuted,
    fontSize: 11,
    fontFamily: bodyFont,
    marginTop: 1,
  },
  previewClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: palette.surfaceSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  previewMeta: {
    color: palette.textMuted,
    fontSize: 11,
    fontFamily: bodyFont,
  },
  previewLoadingText: {
    color: palette.textMuted,
    fontSize: 13,
    fontFamily: bodyFont,
    textAlign: "center" as const,
  },
  previewErrorText: {
    color: palette.danger,
    fontSize: 13,
    fontFamily: bodyFont,
  },
  previewDismiss: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: "500",
    fontFamily: bodyFont,
  },
  previewConfirmButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    height: 48,
    borderRadius: 24,
    backgroundColor: palette.panelDark,
  },
  previewConfirmText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    fontFamily: bodyFont,
  },

  /* ═══════════════════════════════════════════
     CONFIRM SCREEN (light top, dark footer)
     ═══════════════════════════════════════════ */
  confirmPage: {
    flex: 1,
    backgroundColor: palette.backgroundLight,
  },
  confirmContent: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  confirmHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 28,
  },
  confirmTitle: {
    flex: 1,
    color: palette.textPrimary,
    fontSize: 28,
    letterSpacing: -0.8,
    fontWeight: "300",
    fontFamily: displayFont,
    textAlign: "center" as const,
  },
  summaryCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: palette.borderLight,
    backgroundColor: palette.surfaceLight,
    padding: 24,
    gap: 20,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "500",
    textTransform: "uppercase" as const,
    letterSpacing: 1,
    fontFamily: bodyFont,
  },
  summaryValue: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: palette.borderLight,
  },
  summaryAmountValue: {
    color: palette.textPrimary,
    fontSize: 28,
    fontWeight: "700",
    letterSpacing: -0.8,
    fontFamily: displayFont,
  },
  recipientCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  recipientAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.borderLight,
    alignItems: "center",
    justifyContent: "center",
  },
  recipientAvatarText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  recipientName: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: bodyFont,
  },
  recipientAddress: {
    color: palette.textMuted,
    fontSize: 12,
    marginTop: 2,
    fontFamily: bodyFont,
  },
  memoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  memoText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontFamily: bodyFont,
  },
  statusError: {
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: "rgba(220,38,38,0.32)",
    backgroundColor: "rgba(220,38,38,0.06)",
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginTop: 16,
  },
  statusErrorText: {
    color: palette.danger,
    fontSize: 13,
    fontWeight: "500",
    fontFamily: bodyFont,
  },
  statusSuccess: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.borderLight,
    backgroundColor: palette.surfaceLight,
    padding: 20,
    marginTop: 16,
    gap: 10,
    alignItems: "center" as const,
  },
  statusSuccessTitle: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: bodyFont,
    textAlign: "center" as const,
  },
  statusSuccessMeta: {
    color: palette.textMuted,
    fontSize: 12,
    fontFamily: bodyFont,
    textAlign: "center" as const,
  },
  statusLinkButton: {
    borderWidth: 1,
    borderColor: palette.borderLight,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginTop: 4,
  },
  statusLinkText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    fontFamily: bodyFont,
  },
  confirmFooter: {
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    backgroundColor: "#111111",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 40,
  },
  confirmFooterInner: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
});
